services:
  catalog-db:
    image: postgres:17
    container_name: microfilms-catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDB
    ports:
      - "5432:5432"
    volumes:
      - pg_catalog_data:/var/lib/postgresql/data
    networks:
      - microfilms-network
    restart: always
  
  media-db:
    image: postgres:17
    container_name: microfilms-media-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MediaDB
    ports:
      - "5433:5432" # Map port 5433 bên ngoài vào 5432 bên trong
    volumes:
      - pg_media_data:/var/lib/postgresql/data
    networks:
      - microfilms-network
    restart: always
        
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@microfilms.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    networks:
      - microfilms-network
    
  rabbitmq:
    image: rabbitmq:management # Bản management có sẵn UI quản lý
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   # Port giao tiếp TCP
      - "15672:15672" # Port UI Management
    networks:
      - microfilms-network
    
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - microfilms-network
        
networks:
  microfilms-network:
    driver: bridge

volumes:
  pg_catalog_data:
  pg_media_data: